name: 'Pull request check'
description: 'Checks if a pull request meets a set of requirements.'
inputs:
  github-token:
    description: 'GitHub token with read and write access on the project.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
