name: 'Changelog update'
description: 'Update CHANGELOG when pull requests are merged'
inputs:
  github-token:
    description: 'GitHub token with read and write access on the project.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
