
name: 'Milestone propagation'
description: 'Propagate milestone creation/update across an github organization.'
inputs:
  github-token:
    description: 'GitHub token with read and write access on the project.'
    required: true
runs:
  using: "node16"
  main: "index.js"
