name: 'Event Store release'
description: 'Lookup or Create a release on Github'
inputs:
  github-token:
    description: 'GitHub token with read and write access on the EventStore organization.'
    required: true
  build-type:
    description: 'Type of release. It could be nightly, beta or stable'
    required: true
  owner:
    description: 'Target GitHub owner. Default is the current repo owner'
    required: false
  repo:
    description: 'Target GitHub repo. Default is the current repo'
    required: false
  version:
    description: 'The version to release. This is required for a stable release.'
    required: false
  iteration:
    description: 'The package iteration. This is appended to the version. e.g: {version}-{iteration}'
    required: false
outputs:
  version:
    description: 'A version name, like 2020-04-01-nightly'
  release_id:
    description: 'A GitHub release id'
  upload_url:
    description: 'URL used to upload release asset to GitHub'
runs:
  using: "node16"
  main: "index.js"