name: EventStore Triage Project Automations Workflow

on:
  workflow_call:
    inputs:
      resource-node-id:
        required: true
        description: The node id of the issue or PR to act upon
        type: string
      event-action:
        required: true
        description: The event action that triggered the original workflow
        type: string
      labels:
        required: false
        description: The labels on the item as a comma-separated string
        type: string
      triage-status:
        description: The project status to apply to the issue or PR
        default: "To Triage"
        required: false
        type: string
    secrets:
      token:
        required: true
        description: The token to use. It must have org:write access
      project-number:
        required: true
        description: The project number from the project's url

env:
  PROJECT_NUMBER: ${{ secrets.project-number }}
jobs:
  item-milestoned:
    name: Remove milestoned item
    runs-on: ubuntu-latest
    if: inputs.event-action == 'milestoned'
    steps:
      - uses: EventStore/Automations/delete-project-next-item@master
        with:
          github-token: ${{ secrets.token }}
          organization: EventStore
          project-number: ${{ env.PROJECT_NUMBER }}
          resource-node-id: ${{ inputs.resource-node-id }}
  item-added:
    name: Add item to board
    runs-on: ubuntu-latest
    if: inputs.event-action == 'opened' || inputs.event-action == 'reopened' || (inputs.event-action == 'labeled' && contains('triage', inputs.labels))
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.token }}
          organization: EventStore
          project_id: ${{ env.PROJECT_NUMBER }}
          resource_node_id: ${{ inputs.resource-node-id }}
          status_value: ${{ inputs.triage-status }}
